name: percent_indicator_example
description: A new Flutter project.

version: 1.0.0+1
publish_to: "none"

dependencies:
  flutter:
    sdk: flutter

  percent_indicator:
    path: ../
environment:
  sdk: ">=2.12.0-0 <3.0.0"
# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
