name: percent_indicator
description: Library that allows you to display progress widgets based on percentage, can be Circular or Linear, you can also customize it to your needs.
version: 2.1.9+1
homepage: https://www.diegoveloper.com
repository: https://github.com/diegoveloper/flutter_percent_indicator/

dependencies:
  flutter:
    sdk: flutter

environment:
    sdk: ">=2.7.0 <3.0.0"    

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: