name: percent_indicator
description: Library that allows you to display progress widgets based on percentage, can be Circular or Linear, you can also customize it to your needs.
version: 2.0.1
author: Diego Vel√°squez <diegoveloper@gmail.com>
homepage: https://github.com/diegoveloper/flutter_percent_indicator/

dependencies:
  flutter:
    sdk: flutter

environment:
    sdk: ">=1.19.0 <3.0.0"    

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: